# Missing Data

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
states = pd.Series(['alabama', 'california', np.nan, 'minnesota', 'virginia'])
states

In [ ]:
states.isnull()

In [ ]:
states.isnull().any()

In [ ]:
states.isnull().sum()

In [ ]:
states[2] = None

In [ ]:
states.isnull()

In [ ]:
states.dropna()

In [ ]:
states.notnull()

In [ ]:
states[states.notnull()]

In [ ]:
data = pd.DataFrame([
    ['alabama', np.NAN, np.NAN],
    ['california', 39536653, 1246],
    ['minnesota', 5576606, 169],
    [np.NAN, np.NAN, np.NAN],
    ['virginia', 8470020, 222]
])

In [ ]:
data

In [ ]:
data.dropna() # drop any row containing NaN

In [ ]:
data.dropna(how='all') # only drop rows having all NaNs

In [ ]:
data[3] = np.nan
data

In [ ]:
data.dropna(axis=1, how='all') # drop columns having all NaNs

In [ ]:
data.iloc[2, 2] = np.nan
data

In [ ]:
data.dropna(thresh=2) # drop rows having fewer than 2 non-NaN values

In [ ]:
data.fillna(0)

In [ ]:
data.fillna({1:1000000, 2:50})

In [ ]:
data.fillna(data.mean())

In [ ]:
data = pd.DataFrame([
    ['alabama', np.NAN, np.NAN],
    ['california', 39536653, 1246],
    ['virginia', 8470020, 222],
    ['california', 39536653, 1246],
    ['minnesota', 5576606, 169],
    [np.NAN, np.NAN, np.NAN],
    ['virginia', 8470020, 222]
])

In [ ]:
data.duplicated()

In [ ]:
data.drop_duplicates()

# Replacing Text

In [ ]:
dollars = pd.Series(['12', '-$10', '$10,000'])
dollars

In [ ]:
dollars.str.replace('$', '')

In [ ]:
dollars

In [ ]:
dollars = dollars.str.replace('$', '')
dollars

# Regular Expression (regex) Replace

In [ ]:
import re
dollars = pd.Series(['12', '-$10', '$10,000'])
dollars.apply(lambda s: re.sub('\$', '', s))

In [ ]:
states = pd.Series(['Caaliforni.', 'Maaryl.nd', 'Al.baama', 'Virginiaa'])
states

In [ ]:
states.apply(lambda s: re.sub('aa|\.', 'a', s))

In [ ]:
import pandas as pd

In [ ]:
from google.colab import files
files.upload()

Saving states.csv to states.csv

{'states.csv': b'State,Abbrev,Count,Population\nAlabama,AL,129,4874747\nAlaska,AK,35,739795\nAmerican Samoa,AS,1,51504\nArizona ,AZ,155,7016270\nArkansas,AR,108,3004279\nCalifornia,CA,1246,39536653\nColorado,CO,171,5607154\nConnecticut,CT,114,3588184\nDelaware,DE,23,961939\nDistrict of Columbia,DC,33,693972\nFederated States of Micronesia,FM,4,\nFlorida,FL,439,20984400\nGeorgia,GA,210,10429379\nGuam,GU,2,167358\nHawaii,HI,43,1427538\nIdaho,ID,33,1716943\nIllinois,IL,391,12802023\nIndiana,IN,175,6666818\nIowa,IA,107,3145711\nKansas,KS,99,2913123\nKentucky,KY,165,4454189\nLouisiana,LA,173,4684333\nMaine,ME,60,1335907\nMarshall Islands,MH,2,\nMaryland,MD,148,6052177\nMassachusetts,MA,261,6859819\nMichigan,MI,302,9962311\nMinnesota,MN,169,5576606\nMississippi,MS,69,2984100\nMissouri,MO,242,6113532\nMontana,MT,54,1050493\nNebraska,NE,68,1920076\nNevada,NV,77,2998039\nNew Hampshire,NH,43,1342795\nNew Jersey,NJ,207,9005644\nNew Mexico,NM,61,2088070\nNew York,NY,632,19849399\nNorth Carolina,NC,188,10273419\nNorth Dakota,ND,30,755393\nNorthern Mariana Islands,MP,1,\nOhio,OH,386,11658609\nOklahoma,OK,158,3930864\nOregon,OR,125,4142776\nPalau,PW,1,\nPennsylvania,PA,544,12805537\nPuerto Rico,PR,161,3337177\nRhode Island,RI,37,1059639\nSouth Carolina,SC,97,5024369\nSouth Dakota,SD,33,869666\nTennessee,TN,191,6715984\nTexas,TX,506,28304596\nUtah,UT,60,3101833\nVermont,VT,32,623657\nVirgin Islands,VI,2,\nVirginia,VA,222,8470020\nWashington,WA,164,7405743\nWest Virginia,WV,99,1815857\nWisconsin,WI,132,5795483\nWyoming,WY,17,579315\n'}

In [ ]:
data = pd.read_csv('states.csv')
data
# any guesses as to what count represents?

                             State Abbrev  Count  Population
0                          Alabama     AL    129   4874747.0
1                           Alaska     AK     35    739795.0
2                   American Samoa     AS      1     51504.0
3                         Arizona      AZ    155   7016270.0
4                         Arkansas     AR    108   3004279.0
5                       California     CA   1246  39536653.0
6                         Colorado     CO    171   5607154.0
7                      Connecticut     CT    114   3588184.0
8                         Delaware     DE     23    961939.0
9             District of Columbia     DC     33    693972.0
10  Federated States of Micronesia     FM      4         NaN
11                         Florida     FL    439  20984400.0
12                         Georgia     GA    210  10429379.0
13                            Guam     GU      2    167358.0
14                          Hawaii     HI     43   1427538.0
15                           Idaho     ID     33   1716943.0
16                        Illinois     IL    391  12802023.0
17                         Indiana     IN    175   6666818.0
18                            Iowa     IA    107   3145711.0
19                          Kansas     KS     99   2913123.0
20                        Kentucky     KY    165   4454189.0
21                       Louisiana     LA    173   4684333.0
22                           Maine     ME     60   1335907.0
23                Marshall Islands     MH      2         NaN
24                        Maryland     MD    148   6052177.0
25                   Massachusetts     MA    261   6859819.0
26                        Michigan     MI    302   9962311.0
27                       Minnesota     MN    169   5576606.0
28                     Mississippi     MS     69   2984100.0
29                        Missouri     MO    242   6113532.0
30                         Montana     MT     54   1050493.0
31                        Nebraska     NE     68   1920076.0
32                          Nevada     NV     77   2998039.0
33                   New Hampshire     NH     43   1342795.0
34                      New Jersey     NJ    207   9005644.0
35                      New Mexico     NM     61   2088070.0
36                        New York     NY    632  19849399.0
37                  North Carolina     NC    188  10273419.0
38                    North Dakota     ND     30    755393.0
39        Northern Mariana Islands     MP      1         NaN
40                            Ohio     OH    386  11658609.0
41                        Oklahoma     OK    158   3930864.0
42                          Oregon     OR    125   4142776.0
43                           Palau     PW      1         NaN
44                    Pennsylvania     PA    544  12805537.0
45                     Puerto Rico     PR    161   3337177.0
46                    Rhode Island     RI     37   1059639.0
47                  South Carolina     SC     97   5024369.0
48                    South Dakota     SD     33    869666.0
49                       Tennessee     TN    191   6715984.0
50                           Texas     TX    506  28304596.0
51                            Utah     UT     60   3101833.0
52                         Vermont     VT     32    623657.0
53                  Virgin Islands     VI      2         NaN
54                        Virginia     VA    222   8470020.0
55                      Washington     WA    164   7405743.0
56                   West Virginia     WV     99   1815857.0
57                       Wisconsin     WI    132   5795483.0
58                         Wyoming     WY     17    579315.0

In [ ]:
bins = [0, 10, 100, 500, 1000, 2000]

In [ ]:
schools = pd.cut(data['Count'], bins)
schools

0       (100, 500]
1        (10, 100]
2          (0, 10]
3       (100, 500]
4       (100, 500]
5     (1000, 2000]
6       (100, 500]
7       (100, 500]
8        (10, 100]
9        (10, 100]
10         (0, 10]
11      (100, 500]
12      (100, 500]
13         (0, 10]
14       (10, 100]
15       (10, 100]
16      (100, 500]
17      (100, 500]
18      (100, 500]
19       (10, 100]
20      (100, 500]
21      (100, 500]
22       (10, 100]
23         (0, 10]
24      (100, 500]
25      (100, 500]
26      (100, 500]
27      (100, 500]
28       (10, 100]
29      (100, 500]
30       (10, 100]
31       (10, 100]
32       (10, 100]
33       (10, 100]
34      (100, 500]
35       (10, 100]
36     (500, 1000]
37      (100, 500]
38       (10, 100]
39         (0, 10]
40      (100, 500]
41      (100, 500]
42      (100, 500]
43         (0, 10]
44     (500, 1000]
45      (100, 500]
46       (10, 100]
47       (10, 100]
48       (10, 100]
49      (100, 500]
50     (500, 1000]
51       (10, 100]
52       (10, 100]
53         (0, 10]
54      (100, 500]
55      (100, 500]
56       (10, 100]
57      (100, 500]
58       (10, 100]
Name: Count, dtype: category
Categories (5, interval[int64]): [(0, 10] < (10, 100] < (100, 500] < (500, 1000] < (1000, 2000]]

In [ ]:
pd.value_counts(schools)

(100, 500]      27
(10, 100]       21
(0, 10]          7
(500, 1000]      3
(1000, 2000]     1
Name: Count, dtype: int64

In [ ]:
data.describe()

             Count    Population
count    59.000000  5.400000e+01
mean    159.949153  6.097689e+06
std     200.886005  7.216798e+06
min       1.000000  5.150400e+04
25%      36.000000  1.499889e+06
50%     108.000000  4.036820e+06
75%     181.500000  6.977157e+06
max    1246.000000  3.953665e+07

In [ ]:
pd.qcut(data['Count'], 4)

0      (108.0, 181.5]
1       (0.999, 36.0]
2       (0.999, 36.0]
3      (108.0, 181.5]
4       (36.0, 108.0]
5     (181.5, 1246.0]
6      (108.0, 181.5]
7      (108.0, 181.5]
8       (0.999, 36.0]
9       (0.999, 36.0]
10      (0.999, 36.0]
11    (181.5, 1246.0]
12    (181.5, 1246.0]
13      (0.999, 36.0]
14      (36.0, 108.0]
15      (0.999, 36.0]
16    (181.5, 1246.0]
17     (108.0, 181.5]
18      (36.0, 108.0]
19      (36.0, 108.0]
20     (108.0, 181.5]
21     (108.0, 181.5]
22      (36.0, 108.0]
23      (0.999, 36.0]
24     (108.0, 181.5]
25    (181.5, 1246.0]
26    (181.5, 1246.0]
27     (108.0, 181.5]
28      (36.0, 108.0]
29    (181.5, 1246.0]
30      (36.0, 108.0]
31      (36.0, 108.0]
32      (36.0, 108.0]
33      (36.0, 108.0]
34    (181.5, 1246.0]
35      (36.0, 108.0]
36    (181.5, 1246.0]
37    (181.5, 1246.0]
38      (0.999, 36.0]
39      (0.999, 36.0]
40    (181.5, 1246.0]
41     (108.0, 181.5]
42     (108.0, 181.5]
43      (0.999, 36.0]
44    (181.5, 1246.0]
45     (108.0, 181.5]
46      (36.0, 108.0]
47      (36.0, 108.0]
48      (0.999, 36.0]
49    (181.5, 1246.0]
50    (181.5, 1246.0]
51      (36.0, 108.0]
52      (0.999, 36.0]
53      (0.999, 36.0]
54    (181.5, 1246.0]
55     (108.0, 181.5]
56      (36.0, 108.0]
57     (108.0, 181.5]
58      (0.999, 36.0]
Name: Count, dtype: category
Categories (4, interval[float64]): [(0.999, 36.0] < (36.0, 108.0] < (108.0, 181.5] < (181.5, 1246.0]]

In [ ]:
cats = pd.qcut(data['Count'], 4)
pd.value_counts(cats)

In [ ]:
pop = data['Population']
pop[pop > 5_000_000]

In [ ]:
data.set_index('State', inplace=True)

In [ ]:
data

In [ ]:
pop = data['Population']
pop[pop > 5_000_000]